### ISSUE TITLE
Are you aware of GraalVM?

### ISSUE THREAD

**Issue by lostmsu** [ReevaJS/reeva#11]
Just saw this project on lobste.rs , was curious what is the motivation vs [GraalVM's JavaScript engine](https://www.graalvm.org/reference-manual/js/JavaScriptCompatibility/)

**Comment by mattco98** [comment]
Yeah, this project is mostly just for fun/learning. I don't plan to ever "finish" it, but hopefully I can get it in a respectable state at some point.
